### ISSUE TITLE
Weights and biases of BNN are not binarized

### ISSUE THREAD

**Issue by gautamHCSCV** [lucamocerino/Binary-Neural-Networks-PyTorch-1.0#2]
Dear Authors,
The weights and biases of Binary Classifier model is not binary. As per your instructions, I have installed the requirements and ran "python main.py app:yml/nin_cifar10.yml".

I have also changed models under all the conditions of main.py to be BNNClassifier(). The model ran and 2 models were saved in .pth format. I observed the state-dict of both of these models and found them to be in non-binary format in both cases.

Please let me know if I am doing a mistake in implementation or am I making any conceptual mistake to understand BNN.

@lucamocerino @lucamocerino

**Comment by lucamocerino** [comment]
Hi, 
some comments:

- BnnClassifier is a pure binary representation with weights {-1,1}. If you wanna inspect the final weights, try this. 
   - Run python main.py app:yml/bnn_caffenet_cifar10.yml for some epochs. 
   - In the folder 'results' you should find the last checkpoint and the best_epoch weights 
   - You can load the dict and inspect for exaple the  state_dict['feature.4.weight'] and you find the weights are -1,1 
   - It is worth noticing that the weights are store in float format for training and inference purpuse. If you need a real binary format ({0,1}) you can implement a simple converted tool.
   
- Different case for XnorClassifier, there the binarization format includes a scale factor so what you can see in the final weights is something like this: {-0.517, 0.517, 0.517}   ->   0.517 * {-1, 1, 1} which is binary.
