### ISSUE TITLE
bnn_caffetnet_Cifar10 is making error due to certificate

### ISSUE THREAD

**Issue by kyeo95** [lucamocerino/Binary-Neural-Networks-PyTorch-1.0#3]
Below error occurs after running bnn_caffetnet_Cifar10.
I think the process getting Cifar10 dataset is the problem.

"urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1129)>"
How do I solve this?

**Comment by lucamocerino** [comment]
Sorry, actually I cannot reproduce the error. It may be due to changes in pytorch url system.
